# Generated by Django 3.1.4 on 2020-12-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_list_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
