# Generated by Django 3.1.4 on 2020-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20201204_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.IntegerField(),
        ),
    ]
